# Generated by Django 3.2.2 on 2021-06-13 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0003_auto_20210511_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyfob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Only staff will be able to view these notes', null=True, verbose_name='Notes')),
                ('code', models.CharField(max_length=30)),
                ('access_level', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name="Is this the member's active keyfob?")),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
