# Generated by Django 3.2.2 on 2021-10-12 00:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20210714_1540'),
        ('keyfobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Only staff will be able to view these notes', null=True, verbose_name='Notes')),
                ('description', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
