# Generated by Django 3.2.2 on 2021-06-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210511_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='keyfob_code',
        ),
    ]
