# Generated by Django 3.2.2 on 2021-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_person_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='valid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='valid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
