# Generated by Django 3.2.2 on 2021-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210617_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='civicrm_contact_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CiviCRM Contact ID'),
        ),
    ]
