# Generated by Django 3.2.2 on 2022-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Summary')),
                ('active_members_total', models.PositiveIntegerField(default=0, help_text='Total members, of all types', verbose_name='Members')),
                ('active_households_singleperson', models.PositiveIntegerField(default=0, help_text='Households with multiple members', verbose_name='Single-Person Households')),
                ('active_households_multiperson', models.PositiveIntegerField(default=0, help_text='Households with multiple members', verbose_name='Multiperson Households')),
                ('active_student_teams', models.PositiveIntegerField(default=0, verbose_name='Student Teams')),
                ('active_student_team_members', models.PositiveIntegerField(default=0, verbose_name='Student Team Members')),
            ],
        ),
    ]
